### ISSUE TITLE
Ammo Pouch in Classic

### ISSUE THREAD

**Issue by whyttedragun** [doadin/Baggins#11]
"Compress bag contents" button repeatedly tries to put non-ammo items in the ammo pouch for hunters on Classic.  It works properly if the ammo pouch is full.

**Comment by doadin** [comment]
Is there an error you get?

**Comment by whyttedragun** [comment]
No Lua error. Just the regular built in error saying "only ammo can go
there". Same basic thing happens with warlocks and soul pouches.

**Comment by doadin** [comment]
ok thanks for the info, Ill update when I know more.

**Comment by doadin** [comment]
Not necessarily related info but a few things. It seems some items might be miss categorized and therefore its trying to put items in the pouch that shouldn't be. I don't play classic very much so I only have one of the special bag classes and thats a hunter at lvl 10... I did however find some keyring code that had been "nuked" since retail doesn't have keyrings since 4.2. This may or maynot have been the miss categorized items, really not sure. However if the issue still occurs after the update(v3.2.3) let me know.

**Comment by doadin** [comment]
https://github.com/doadin/Baggins/pull/16
