### ISSUE TITLE
Currently equipped weapon/armor are showing in bags

### ISSUE THREAD

**Issue by Anemun** [doadin/Baggins#112]
Good day to you! I'm playing Cataclysm Classic, russian language.
After updating to the new version of Baggins 5.2.0-cata, the inventory now displays items that are currently equipped on the character: weapons, armor, and some (but not all) bags.
![baggins-issue](https://github.com/doadin/Baggins/assets/15797528/683ff952-ff62-40c7-b088-5668c3392c9b)

**Comment by Elberet** [comment]
I have the same issue as OP, also on Cataclysm Classic with the english language client.

I've also tried downgrading to v5.1.9 and v5.1.8 without success, so presumably the Small Indie Company silently changed some APIs?

**Comment by doadin** [comment]
Apparently there was api for keyring in cata ,maybe left over from wrath? idk but apparently keyring is not a thing in cata? Thats part of the issue second part is for some reason Baggins thinks items equiped is in the keyring, im trying to look into it. Sorry for this.

**Comment by Anemun** [comment]
empty keyring slots are gone, thank you! equipped items are still showing in bags, looking forward for the fix

**Comment by Elberet** [comment]
Commenting out these two lines removes equipment slots from Baggins:

https://github.com/doadin/Baggins/blob/eb29b2d89f729c7caedc10f04479f0d6f5d69e5d/Baggins-Filtering.lua#L446-L447

Seems related to the changes to how the bank is handled, since bank slots are no longer retrieved as slots in bag -1, but through the character inventory API?

**Comment by Anemun** [comment]
> Commenting out lines 446 and 447 in `ForceFullUpdate()` removes equipment slots from Baggins:
> 
> https://github.com/doadin/Baggins/blob/eb29b2d89f729c7caedc10f04479f0d6f5d69e5d/Baggins-Filtering.lua#L441-L449
> 
> Seems related to the changes to how the bank is handled, since bank slots are no longer retrieved as slots in bag -1, but through the character inventory API?

worked for me, thanks!

**Comment by Elberet** [comment]
Yeah, you also need to change the comparison in [Baggins.lua:1155](https://github.com/doadin/Baggins/blob/eb29b2d89f729c7caedc10f04479f0d6f5d69e5d/Baggins.lua#L1155) from `<= 4` to `< 0`.

**Comment by Anemun** [comment]
> Yeah, you also need to change the comparison in [Baggins.lua:1155](https://github.com/doadin/Baggins/blob/eb29b2d89f729c7caedc10f04479f0d6f5d69e5d/Baggins.lua#L1155) from `<= 4` to `< 0`.

that worket, thank you

**Comment by doadin** [comment]
@Elberet @Anemun maybe you guys can confirm, but making those changes breaks the bank updating, puting items in or removing and bank bags never update, even if I close bank and go back.

**Comment by Elberet** [comment]
Yeah, it's most likely the change in `Baggins:OnBagUpdate` that the bank. I believe the `BAG_UPDATE` event still sends `-1` when the bank contents were updated, even tho items in that bank should really be queried through the inventory API instead of the container API. I really just hacked the thing so I could play the game. 😉 

That said, I've changed the conditional to `if bagid < -1 then return end` and that seem to allow bank updates as normal.

At least in Cataclysm right now. I haven't the foggiest how any of these changes would affect classic or retail.

**Comment by doadin** [comment]
@Elberet @Anemun I have commited this change and pushed out a release with it, https://github.com/doadin/Baggins/commit/a68c391a53473a59da08d821b90759ed39f5a122 . This seemed to work including bank updating and changes only apply to cata, Other wow versions don't appear to have this issue, either they are not using new api or there is a bug in the cata api, either way for now this change will only apply to cata. Let me know if you guys still have issues.
