### ISSUE TITLE
Splitting an item in your inventory to be the max amount?

### ISSUE THREAD

**Issue by sonnyha** [doadin/Baggins#53]
This is my first time submitting an issue on GitHub ever, so please excuse me if I'm not doing this correctly!

I sell a lot of things in the AH and sometimes when I want to sell an item and the max stack of that item is say 20 and I have 23 total. When I click and drag that item to the auction slot, I will automatically pull the 3 from the total amount when really I want the max amount. 

I'll then put the 3 leftover into a random bag and look for the max stack but cannot find it because it is in the first bag, However, when I click the first bag my Baggins will open which leaves me back to my original problem. Is there a way around this or is there something within the options menu that can solve this?

**Comment by doadin** [comment]
If I am understanding correctly, the problem comes from Baggins compressing items so what you see is not actually the stack of items but just how much you have, and when you select the item it doesn't select the max stack just a stack. So you end up dragging a 3 stack of something instead of a 20 stack. I would think if you disable compressing it will show each stack of an item and then you can choose to drag the stack you want to put in the AH.

**Comment by doadin** [comment]
If I am right in the baggins config go to Items > Compress > Uncheck "Compress Stackable Items"

**Comment by sonnyha** [comment]
This fixed it! I didn't realize there was a '+' to expand everything. Thank you so much!
